{{- if .Values.client.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    application: {{ template "name-client" . }}
  name: {{ template "name-client" . }}
  namespace: {{ $.Release.Namespace }}
spec:
  ingress:
  - ports:
    # metrics
    - port: 8090
      protocol: TCP
  podSelector:
    matchLabels:
      application: {{ template "name-client" . }}
  policyTypes:
  - Ingress

{{ end }}