{{- if .Values.client.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name-client" . }}-api
  namespace: {{ $.Release.Namespace }}
  labels:
    application: {{ template "name-client" . }}
spec:
  ports:
  - name: api
    port: 8082
    targetPort: 8082
  selector:
    application: {{ template "name-client" . }}
  sessionAffinity: None
  type: ClusterIP
{{ end }}