---
apiVersion: v1
kind: Service
metadata:
  name: wormhole-server
  labels:
    application: wormhole-server
spec:
  ports:
  - name: data
    port: 8080
    targetPort: 8080
  - name: admin
    port: 8081
    targetPort: 8081
  selector:
    application: wormhole-server
  sessionAffinity: None
  type: LoadBalancer
