---
apiVersion: v1
kind: Service
metadata:
  name: wormhole-server
  labels:
    application: wormhole-server
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    application: wormhole-server
  sessionAffinity: None
  type: ClusterIP
