---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: wormhole-mocks
  namespace: mocks
  name: wormhole-mocks
spec:
  replicas: 1
  selector:
    matchLabels:
      application: wormhole-mocks
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        application: wormhole-mocks
    spec:
      containers:
        - image: ghcr.io/glothriel/wormhole:latest
          name: wormhole
          imagePullPolicy: Always
          command:
            - /usr/bin/wormhole
            - testserver
            - --port
            - "8080"
