name: Integration
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install development package
        run: |
          cd test && python setup.py develop

      - name: Run test suite
        run: |
          py.test --tb=short -v
